### ISSUE TITLE
Doesnt work on IE11

### ISSUE THREAD

**Issue by piskinfatih** [devias-io/react-material-dashboard#1]
Hey, great job,

You might have a look if you consider IE

![image](https://user-images.githubusercontent.com/15312526/57412809-bf7e5100-71fa-11e9-8618-4c8fadb470db.png)

**Comment by andrewmclagan** [comment]
This seems like a good place for a pull-request @piskinfatih would you like to try?

**Comment by devias-io** [comment]
Thank you for the contribution guys, we will look into it and try to fix it. If you find a solution we would be happy to accept pull requests!

**Comment by piskinfatih** [comment]
Fix with pull request #3

**Comment by devias-io** [comment]
As we mentioned in the PR, we decided to add a documentation with the necessary steps for the polyfill to maintain a reduced bundle size instead of adding old browser support by default.

Thank you,
Devias Team

**Comment by dnbr2002** [comment]
Any word on this polyfill doc for your template?  I'm having issue with IE as well.

**Comment by devias-io** [comment]
Tomorrow we will update the docs for react-scripts 3.0.
