### ISSUE TITLE
Firebase configs?  

### ISSUE THREAD

**Issue by dnbr2002** [devias-io/react-material-dashboard#12]
Thinking for you pro you could have docs for firebase maybe?   If so I mocked up a version of your free template with Firebase [here](https://github.com/dnbr2002/react-material-dashboard).  :)

**Comment by devias-io** [comment]
Wow, thank you for your efforts @dnbr2002 !! We will take a close look at your repo and we'll come back with a message. Nice work, we like it!

**Comment by dnbr2002** [comment]
I left generic.  It's just ReactContextApi and FirebaseAuth.  Looking forward to that pro version of yours.
