### ISSUE TITLE
Not Able to run the app using npm run start

### ISSUE THREAD

**Issue by nassirgn** [devias-io/react-material-dashboard#15]
Hello 

I get the error below whenever I try to run: npm run start. 

Thanks

======================
Starting the development server...

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-dashboard-react@1.7.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-dashboard-react@1.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mamadoudiallo\AppData\Roaming\npm-cache\_logs\2019-07-02T18_25_17_574Z-debug.log

**Comment by devias-io** [comment]
Hi @nassirgn! Sorry for late response. What version of node/npm are you using?

Thank you!

**Comment by ondhaondhi** [comment]
i got the same problem with node v8.15.0 , please help

**Comment by patrickdemers6** [comment]
Have you run `npm i` before running the command?
