### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by shawnkoh** [devias-io/react-material-dashboard#16]
Hi, I'm really grateful for you guys open-sourcing this really nice and useful example.

Sorry this is not an issue but I'm just wondering if there are any plans to add Typescript support to this library?

Cheers

**Comment by devias-io** [comment]
Hi @shawnkoh, sorry for late response, we've been really busy these days.

It would be nice to. We will discuss this and we will let you know.

Thanks for the feedback!

**Comment by hinsxd** [comment]
Same question here. This theme is much cleaner than the fancy Material Kit.
I am willing to contribute to writing types, or even rewriting with typescript if needed.
I hope your team can create a typescript branch and let people participate in it. Thanks.

**Comment by picosix** [comment]
I'm also want to contribute to typescript branch. Please let me know when you have plan to support typescript. Thanks

**Comment by hinsxd** [comment]
My first try. Themes and layout typing done.
https://github.com/hinsxd/react-material-dashboard-typescirpt

**Comment by frontend210** [comment]
Hi @devias-io  I am also really want to get involved in contributing your project.
