### ISSUE TITLE
error dev dependency

### ISSUE THREAD

**Issue by jrgonzalez3** [devias-io/react-material-dashboard#23]
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^6.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

**Comment by colathro** [comment]
For everyone just starting out with npm and not sure what to do here:

Using yarn will likely fix this; but I managed to just delete packages-lock.json, node_modules, and then within package.json remove the eslint line from devdependencies.
