### ISSUE TITLE
Injected unwanted css on main component after build

### ISSUE THREAD

**Issue by siboscol** [devias-io/react-material-dashboard#24]
I'm using Material UI and I'm still learning about css-in-js and jss in general.
The problem is that I get a jss style injected on the top level element that attachs an unwanted padding. This happen **only** when I build the with react-build.
Above problem mess with the layout and after switching between views it gets fixed.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/6Eb2h.png

I'm basing the project upon this template.
and the inject class happen at following element https://github.com/devias-io/react-material-dashboard/blob/master/src/layouts/Main/Main.js#L47

**Comment by devias-io** [comment]
Hi there! We released a new version if you want to try it.
