### ISSUE TITLE
Remove the components as a folder and have only the component per file

### ISSUE THREAD

**Issue by dimacros** [devias-io/react-material-dashboard#26]
I have seen this component structure when several files work together. For example: The "**SearchInput**" folder has the files: `SearchInput.js`,
`SearchInput.css`, `SearchInput.test.js` and `index.js`, in this case that type of structure makes sense, but you are already using material-ui that has components ready and that allows you to customize the styles within the same component, then It makes no sense to use the folder structure. So my recommendation is that only **`SearchInput.js`** be left so that the project is not unnecessarily indexed. I also propose to eliminate the `node-sass` dependency because I consider that material-ui, it gives you many ways to customize its components and a better performance is achieved if only one tool is used for styles.

**Comment by devias-io** [comment]
Hi dimacros,

It's up to you to decide how you structure your components. We thought that users might add testings, types (Typescript) and we decided to keep the structure with folders.

Regarding the `node-sass` you're right. We will remove the dependency.

Thank you,
Devias Team
