### ISSUE TITLE
Slide Menu is not closing

### ISSUE THREAD

**Issue by a2zyardsale** [devias-io/react-material-dashboard#27]
Hi,
Thanks for the awesome framework. I am try this framework for my personal project. I am facing an issue with the Slide Menu. When the page is render in a small window the side menu became burger menu. When we click the burger menu, it slides from the right. If we click any of the navigation link, the menu is not closing but in page renders properly.  Please let me know is there is any workaround.
Thanks.

**Comment by devias-io** [comment]
Hi! We released a new version that includes this fix.
