### ISSUE TITLE
Plans to support Typescript?

### ISSUE THREAD

**Issue by JamesMcMahon** [devias-io/react-material-dashboard#38]
I am evaluating this dashboard for use with a product I am building. Are there any plans to support Typescript or third-party mechanisms to enable Typescript support?

Sorry if this is a repeat of https://github.com/devias-io/react-material-dashboard/issues/16. It was closed and I didn't want to piggyback on a closed issue.

**Comment by martijnpieters** [comment]
Seems to me this should be easy to answer. There is a plan or not. Based on 3+ months waiting for a yes/no answer, it sounds like the answer is "no". Which is a pity and a reason for me to not use it professionally.

**Comment by devias-io** [comment]
> Seems to me this should be easy to answer. There is a plan or not. Based on 3+ months waiting for a yes/no answer, it sounds like the answer is "no". Which is a pity and a reason for me to not use it professionally.

Hi Martin,
Sorry for not getting back to you, we've been busy working on the PRO version and did not focus on this project. The PRO version is available for both JS and TS. For now, we do not plan to add a TS version for this project.
