### ISSUE TITLE
I'm unable to run dashboard

### ISSUE THREAD

**Issue by pedapudiashok** [devias-io/react-material-dashboard#42]
npm install
npm start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^6.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  /Videos/react-material-dashboard-master/node_modules/eslint (version: 5.16.0) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

**Comment by gordonTang2049** [comment]
Me too, same issue

**Comment by junaidTni** [comment]
update the eslint to 
"eslint": "^6.6.0"

And now it will run on browser correclty

**Comment by iamnikk** [comment]
Just Remove The `"eslint": "5.16.0",`  from `package.json` in `devDependencies` then it will fix.

**Comment by devias-io** [comment]
Hi there, we just released an updated version. This should now be fixed.
