### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by oliviertassinari** [devias-io/react-material-dashboard#5]
Hi guys, thank you for sharing this theme!

I have taken the time to look at the implementation, you can find my feedback in the following list:

- `recompose` this package was soft deprecated. With the growing React hooks trend, it will soon no longer be needed.
- We have solved a lot of issue in Material-UI v4. The beta version starts to be a good shape. You can consider upgrading. I hope it will solve the pain points you faced.
- Are the `!important` really needed in the CSS files?
- `styles.jsx` I personally prefer to have the styles in the same file, but I understand the logic, why not :)
- In v4, tree sharing work, if you upgrade, you can do:
```diff
-import Typography from '@material-ui/core/Typography';
-import IconButton from '@material-ui/core/IconButton';
+import { IconButton, Typography } from '@material-ui/core';
```
- They are a couple of class component that could be written with a simple function. For instance:
```jsx

class PortletHeader extends Component {
  render() {
    const {
```
- Facebook and Google, we could potentially host these icons in Material-UI directly 🤔.
- For the typography, you might want to use the `component` property to define a better HTML semantic structure. For instance, here it's h1, h6
```jsx
            <div className={classes.content}>
              <Typography variant="h1">
                404: The page you are looking for isn’t here
              </Typography>
              <Typography variant="subtitle2">
```

I wish I could look deeper, I hope it helps.

**Comment by devias-io** [comment]
Hi Oliver, thank you for taking your time. These are really awesome tips & we'll implement asap!! Probably not in the next commit due to the volume of refactoring for v4 but in the next days for sure. Thanks!!!
