### ISSUE TITLE
Issue with Ansi Styles??

### ISSUE THREAD

**Issue by dnbr2002** [devias-io/react-material-dashboard#8]
I downloaded the template, ran install without error.  But when I run it, I get a blank page and this error in the console.  

> index.js:69 Uncaught TypeError: Cannot read property 'close' of undefined
>     at Object.<anonymous> (index.js:69)
>     at Object../node_modules/react-dev-utils/node_modules/chalk/index.js (index.js:229)
>     at __webpack_require__ (bootstrap:781)
>     at fn (bootstrap:149)
>     at Object../node_modules/react-dev-utils/formatWebpackMessages.js (formatWebpackMessages.js:11)
>     at __webpack_require__ (bootstrap:781)
>     at fn (bootstrap:149)
>     at Object../node_modules/react-dev-utils/webpackHotDevClient.js (webpackHotDevClient.js:23)
>     at __webpack_require__ (bootstrap:781)
>     at fn (bootstrap:149)

I've done some looking around, this error seems common enough but I'm not sure how to fix it in this template.  Index.js:69 is 

`ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g'); `

I don't see a specific reference to Ansi-styles in root package.json,  Perhaps it's a transitive depends?

**Comment by devias-io** [comment]
We are looking into that, and will come back with an answer

**Comment by devias-io** [comment]
Indeed, we do not use Ansi-styles directly in our `package.json`. Can you provide your Node version?
Also, meanwhile try to clean your project and reinstall the dependencies:

```
rm -rf node_modules
rm yarn.lock
yarn
```

**Comment by dnbr2002** [comment]
so I removed node_modules and yarn lock.  I actually installed Yarn (I was using NPM before).  When I ran the Yarn cmd to install packages it indicated my version (Node.js 8.9.4) was below what was required.  It wanted I think at least an 8.11.x version??  My cmd screen cleared and I can't remember which exact version it was.  I updated to latest Node.js LTS (Node.js 10.15.3) and now everything works.

**Comment by devias-io** [comment]
I believe React requires at least `8.10.x` Node version as specified in the [create-react-app](https://facebook.github.io/create-react-app/docs/getting-started) tutorial.

Glad the update fixed your problem!


Happy coding,
Devias Team

**Comment by nemanjam** [comment]
I have the same error on node `v10.14.1`, npm `v6.4.1`, windows `8.1`. I don't want to install yarn.

`TypeError: ansiStyles.color is undefined[Learn More] index.js:69`

`ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');`

**Comment by devias-io** [comment]
Hi! As already mentioned, this is not a module used directly in our project, it is part of `react-scripts`, but we will look into that to see if there is a workaround this dependency problem.

**Comment by devias-io** [comment]
We've been doing some tests with different Node versions (`v10.14.0`, `v.10.14.1`, `v12.2.0`) with default npm version in each case, on an `Windows 8.1 PRO 64bit (build 6.3, 9600)` machine using `npm` and not `yarn` and worked as expected.

Did you clean your npm cache before the installation? If not please run: 

```
rm -rf node_modules
rm package-lock.json
npm clean cache --force
npm install
npm run start
```

We tested the project on different platforms and hosting services and we never had a problem with the installation. So, it might be a problem with your particular machine.

**Comment by nemanjam** [comment]
I cleaned the cache and reinstalled, the same error persists.

**Comment by devias-io** [comment]
Sorry this is not from our end, you might need to search on google.

**Comment by Laurensdc** [comment]
@devias-io  `npm cache clean --force` not `npm clean cache --force`
Also can't start up my project on a new machine all of a sudden. Clearning cache / reinstalling node_modules / nothing works.

**Comment by bram-codes** [comment]
I know this is issue is closed but this is the first result I get when I search for this error. I'm posting the solution that worked for me in case someone finds this issue.

I had to run `npm i --save-dev chalk@2.4.2 ansi-styles@3.2.1`.
([Found in this comment](https://github.com/facebook/jest/issues/6068#issuecomment-538152240))
