### ISSUE TITLE
Failed to complie

### ISSUE THREAD

**Issue by iamsohel** [devias-io/react-material-dashboard#9]
I have installed all the dependencies successfully. But when i run the command: npm run start
this shows below error

Failed to compile
./node_modules/react-perfect-scrollbar/dist/css/styles.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-perfect-scrollbar/dist/css/styles.css)
Error: Cannot find module '@csstools/normalize.css'

**Comment by devias-io** [comment]
Hi there!

To be able to replicate problem, please provide information about your environment: 
- Node version
- npm version
- OS (Windows, Mac, Linux...)

The error is generated by one of the modules from `package.json`, `react-perfect-scrollbar`. The problem might be your Node version, please upgrade to the latest stable version of Node. If you need to maintain your current version for some other project, we suggest using `nvm`. By doing this you will be able to switch between versions.

Thank you,
Devias Team

**Comment by iamsohel** [comment]
Thanks for  response
 my node version is : 8.10.0
       npm version is : 3.5.2
       OS: Linux (Ubuntu 18.04.2 LTS )

**Comment by devias-io** [comment]
It seems that you're using an old version of npm. By default Node 8.10.0 has npm 5.6.0. Please update your npm version and try again.

**Comment by iamsohel** [comment]
Thanks. It's solved

**Comment by sajidunnar** [comment]
Hey Can u please help me with this issue

import { Dashboard as DashboardLayout } from "layouts" does not work but following works 
import { Dashboard as DashboardLayout } from "..//..//layouts";
